services:
  db:
    image: postgres:latest
    container_name: postgres
    env_file:
      - ./pg/.env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d policies"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./data/db:/var/lib/postgresql/data

  backend:
    build: .
    container_name: backend
    env_file:
      - ./api/.env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
volumes:
  db:
